.\" Copyright (c) 2021 Sergey Bronnikov
.\"
.Dd $Mdocdate: April 15 2021 $
.Dt UNRELIABLEFS.CONF 5
.Os
.Sh NAME
.Nm unreliablefs.conf
.Nd format of the configuration file used by
.Xr unreliablefs 1
.Sh DESCRIPTION
The configuration file format is quite simple.
Sections are delimited by square brackets:
.Pp
.Rs
[Section]
.Re
.Pp
And options within brackets sections are simple key value pairs:
.Pp
.Rs
Option = Value
.Re
.Sh OPTIONS
Per-fault-injection customizable variables are specified within sections
with section names matching the fault-injection name.
.Pp
Supported fault injections are:
.Bl -tag -width Ds
.It Cm errinj_noop
File operation replaced with no-op.
.It Cm errinj_kill_caller
Send SIGKILL signal to a process that invoked file operation.
.It Cm errinj_errno
Set random errno.
.Xr errno 2
limited by supported errno's.
.It Cm errinj_slowdown
File operation slowdown for nanoseconds specified by duration parameter.
.El
.Pp
The options are:
.Bl -tag -width Ds
.It Cm op_regexp
Sets the regular expression that matches file operation for what fault injection is applicable.
Option uses format of regular expressions described in
.Xr re_format 7 .
POSIX Extended Regular Expression syntax is supported and regular expressions do not differentiate case.
.It Cm path_regexp
Sets the regular expression that matches paths where fault injection is applicable.
Option uses format of regular expressions described in
.Xr re_format 7 .
POSIX Extended Regular Expression syntax is supported and regular expressions do not differentiate case.
.It Cm probability
Sets the probability in percents.
Probability equal to 0 means that error injection will never happen.
Probability equal to 100 means that error injection will happen on each file operation.
.It Cm duration
Sets the duration of file operation slowdown.
Applicable to errinj_slowdown only.
.El
.Sh EXAMPLES
.Bd -literal

[errinj_noop]
path_regexp = .*
op_regexp = .*
probability = 70

[errinj_errno]
path_regexp = *.xlog
probability = 4

.Ed
.Sh SEE ALSO
.Xr unreliablefs 1 ,
.Xr errno 2 ,
.Xr syslog 3 ,
.Xr re_format 7
.Sh AUTHORS
.An -nosplit
The
.Xr unreliablefs 1
utility was written by
.An Sergey
.An Bronnikov .
.\" .Sh HISTORY
.\" .Sh BUGS
.\" .Sh CAVEATS
