ubuntu_1804: &ubuntu_1804
  container:
    image: ubuntu:bionic
  env:
    UBUNTU_CODENAME: bionic

ubuntu_1804_gcc: &ubuntu_1804_gcc
  <<: *ubuntu_1804
  env:
    CC: gcc-9
  bootstrap_script:
    - apt-get update
    - apt-get install -y gnupg2 ca-certificates wget curl
    - |
      cat << EOF > /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu ${UBUNTU_CODENAME} main
      deb-src http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu ${UBUNTU_CODENAME} main
      EOF
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1E9377A2BA9EF27F
    - apt-get update
  install_script:
    - apt-get install -y cmake gcc-9 g++-9 libc-dev build-essential fuse libfuse-dev mandoc python-pytest

ubuntu_1804_clang: &ubuntu_1804_clang
  <<: *ubuntu_1804
  env:
    CC: clang-10
    CLANG_VERSION: 10
  bootstrap_script:
    - apt-get update
    - apt-get install -y gnupg2 ca-certificates wget curl
    - |
      cat << EOF > /etc/apt/sources.list.d/llvm-toolchain.list
      deb https://apt.llvm.org/${UBUNTU_CODENAME} llvm-toolchain-${UBUNTU_CODENAME}-${CLANG_VERSION} main
      deb-src https://apt.llvm.org/${UBUNTU_CODENAME} llvm-toolchain-${UBUNTU_CODENAME}-${CLANG_VERSION} main
      EOF
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
    - apt-get update
  install_script:
    - apt-get install -y cmake clang-${CLANG_VERSION} libc-dev build-essential fuse libfuse-dev mandoc python-pytest
    - update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${CLANG_VERSION} 10

macos_1015: &macos_1015
  osx_instance:
    image: catalina-base
  env:
    CC: clang
  install_script:
    - brew install --cask osxfuse
    - brew install cmake python3
    - sudo python3 -m pip install pytest

macos_1101: &macos_1101
  osx_instance:
    image: big-sur-base
  install_script:
    - brew update-reset
    - brew upgrade
    - brew install --cask osxfuse
    - brew install cmake python3
    - sudo python3 -m pip install pytest

freebsd_12_2: &freebsd_12_2
  freebsd_instance:
    image: freebsd-12-2-release-amd64
  env:
    CC: clang
  install_script:
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f; pkg install -y cmake fusefs-libs pkgconf python3 py37-pip
    - kldload fuse
    - kldstat
    - sudo python3.7 -m pip install pytest

task:
  matrix:
    - name: "Build and test on Ubuntu 18.04 LTS with GCC 9"
      <<: *ubuntu_1804_gcc
    - name: "Build and test on Ubuntu 18.04 LTS with Clang 10"
      <<: *ubuntu_1804_clang
    - name: "Build and test on FreeBSD 12.2"
      <<: *freebsd_12_2
    - name: "Build and test on macOS 10.15 (Catalina)"
      <<: *macos_1015
    - name: "Build and test on macOS 11.0.1 (Big Sur)"
      <<: *macos_1101

  build_script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make

  test_script:
    - pytest --verbose --junit-xml=report.xml tests/
