ubuntu_1804: &ubuntu_1804
  container:
    image: ubuntu:bionic
  env:
    UBUNTU_CODENAME: bionic

ubuntu_2104: &ubuntu_2104
  container:
    image: ubuntu:hirsute
  env:
    UBUNTU_CODENAME: hirsute

ubuntu_1804_gcc: &ubuntu_1804_gcc
  <<: *ubuntu_1804
  env:
    CC: gcc-7
  bootstrap_script:
    - apt-get update
  install_script:
    - apt-get install -y cmake libc-dev build-essential fuse libfuse-dev mandoc  python-dev python3-dev python3-pytest fio

ubuntu_1804_clang: &ubuntu_1804_clang
  <<: *ubuntu_1804
  env:
    CC: clang
  bootstrap_script:
    - apt-get update
  install_script:
    - apt-get install -y cmake libc-dev build-essential fuse libfuse-dev mandoc  python-dev python3-dev python3-pytest fio clang

ubuntu_2104_gcc: &ubuntu_2104_gcc
  <<: *ubuntu_2104
  env:
    CC: gcc
    DEBIAN_FRONTEND: noninteractive
  bootstrap_script:
    - apt-get update
  install_script:
    - apt-get install -y cmake libc-dev build-essential fuse libfuse-dev mandoc python3-pytest fio

ubuntu_2104_clang: &ubuntu_2104_clang
  <<: *ubuntu_2104
  env:
    CC: clang-12
    DEBIAN_FRONTEND: noninteractive
  bootstrap_script:
    - apt-get update
  install_script:
    - apt-get install -y cmake libc-dev build-essential fuse libfuse-dev mandoc python3-pytest fio clang-12

macos_1101: &macos_1101
  osx_instance:
    image: big-sur-base
  install_script:
    - brew update-reset
    - brew upgrade
    - brew install --cask osxfuse
    - brew install cmake python3 fio
    - sudo python3 -m pip install pytest

freebsd_12_2: &freebsd_12_2
  freebsd_instance:
    image: freebsd-12-2-release-amd64
  env:
    CC: clang
  install_script:
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f; pkg install -y cmake fusefs-libs pkgconf python3 py37-pip fio
    - kldload fuse
    - kldstat
    - sudo python3.7 -m pip install pytest

task:
  matrix:
    - name: "Build and test on Ubuntu 18.04 LTS with GCC 7"
      <<: *ubuntu_1804_gcc
    - name: "Build and test on Ubuntu 18.04 LTS with Clang 6"
      <<: *ubuntu_1804_clang
    - name: "Build and test on Ubuntu 21.04 with GCC 10"
      <<: *ubuntu_2104_gcc
    - name: "Build and test on Ubuntu 21.04 with Clang 12"
      <<: *ubuntu_2104_clang
    - name: "Build and test on FreeBSD 12.2"
      <<: *freebsd_12_2
    - name: "Build and test on macOS 11.0.1 (Big Sur)"
      <<: *macos_1101

  build_script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make

  test_script:
    - make -C build pytest

  always:
    junit_artifacts:
      path: "report.xml"
      format: junit
      type: text/xml
